// Generated by scripts/gen_constants.py; do not edit by hand.
pragma circom 2.2.3;

function MAX_TICK_SPACING() { return 354892; }
function MAX_SWAP_STEPS() { return 16; }
function MAX_INPUT_NOTES() { return 4; }
function MAX_FEE_GROWTH() { return 0x800000000000011000000000000000000000000000000000000000000000000; }
function TREE_HEIGHT() { return 32; }

template ZeroLeafHash() {
    signal output out;
    out <== 0x293d3e8a80f400daaaffdd5932e2bcc8814bab8f414a75dcacf87318f8b14c5;
}
