// Generated by scripts/gen_constants.py; do not edit by hand.
pub const TREE_HEIGHT: usize = 32;
pub const ZERO_LEAF_HASH_HEX: &str = "0x293d3e8a80f400daaaffdd5932e2bcc8814bab8f414a75dcacf87318f8b14c5";
