// Generated by scripts/gen_constants.py; do not edit by hand.
pub const MAX_TICK_SPACING: u128 = 354892;
pub const MAX_SWAP_STEPS: usize = 16;
pub const MAX_INPUT_NOTES: usize = 4;
pub const TREE_HEIGHT: usize = 32;
pub const MAX_FEE_GROWTH_HEX: &str = "0x800000000000011000000000000000000000000000000000000000000000000";
pub const ZERO_LEAF_HASH_HEX: &str = "0x293d3e8a80f400daaaffdd5932e2bcc8814bab8f414a75dcacf87318f8b14c5";
